[ED-42, ED-43, ED-58] Verificar usuario logueado y agregar cursos
Team-Invasores-of-Venezuela/invasionofvenezuelaP2 pull request #26
Opened 2024-11-16 22:58 UTC by ktax06

ED-42: vista
ED-43: verificar si el usuario está logueado
ED-58: Agregar curso

2024-11-16 23:47 UTC, Yankito requested changes
Por favor, confirma los cambios indicados. Principalmente se está eliminando la implementación de las imagenes de los cursos

2024-11-16 23:47 UTC, Yankito commented on frontend-edunerd/src/app/curso-admin/curso-admin.component.html
> -          [src]="curso.imagen"
ya no se va a usar una imagen para el curso?

2024-11-16 23:47 UTC, Yankito commented on frontend-edunerd/src/app/estudiante-admin/estudiante-admin.component.html
> +        <button  class="px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600">Subir</button>
no se está usando el método de subir archivo que implementó Franco

2024-11-16 23:47 UTC, Yankito commented on frontend-edunerd/src/app/curso-admin/curso-admin.component.ts
> -
esta funcion ya no se utiliza?

2024-11-16 23:51 UTC, ktax06 commented on frontend-edunerd/src/app/curso-admin/curso-admin.component.html
> -          [src]="curso.imagen"
no, ya no se va a usar una imagen

2024-11-17 00:01 UTC, Yankito requested changes
quedan dos cambios que indiqué, para que los respondas por favor

2024-11-17 00:09 UTC, closed without merging